- name: Install Apache
  apt:
    name: "{{ apache_packages }}"
    state: present
    update_cache: yes
  notify: restart apache

- name: webpagina
  copy:
    content: "<h1>Hello world</h1>"
    dest: /var/www/html/index.html
